version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    networks:
      - saleor-backend-tier
      - saleor-frontend-tier
    volumes:
      - /Users/kennethonah/docker/apps/saleor:/app:cached
    env_file: common.env
    depends_on:
      - db
      - redis

  db:
    image: library/postgres:11.1-alpine
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - /Users/kennethonah/.docker/data/redis:/data

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file: common.env
    depends_on:
      - redis

volumes:
  db:
    driver: local
  redis:
    driver: local

networks:
  saleor-backend-tier:
    driver: bridge
  saleor-frontend-tier:
    driver: bridge
